server:
  port: ${PORT:8080}
spring:
  datasource:
    url: ${jdbc:postgresql://bookpoisk_user:7doZ5AVgGutm4z6bWpqVbY38IxrkwQeE@dpg-d37dt9hr0fns739e5vdg-a/bookpoisk}
    username: ${bookre}
    password: ${lovemom0405}
  jpa:
    hibernate:
      ddl-auto: update # Hibernate сам создаёт/обновляет таблицы по сущностям
    properties:
      hibernate:
        format_sql: true # true — красиво печатает SQL в логах.
        jdbc.time_zone: UTC # пишет/читает время в UTC.
  open-in-view: false # сессия закрывается до контроллера
