spring:
  datasource:
    url: jdbc:postgresql://dpg-d37dt9hr0fns739e5vdg-a.oregon-postgres.render.com:5432/bookpoisk?sslmode=require
    username: bookpoisk_user
    password: 7doZ5AVgGutm4z6bWpqVbY38IxrkwQeE
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080
